# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aFc9BitYs3IwEIzIe7Uv0uDEZuCeICGl
"""

import streamlit as st 
from PIL import Image

img = Image.open("bmi.jpg")
st.image(img)

# Input

weight = st.number_input("Enter your Weight in KG", step = 0.1)

height = st.number_input("Enter your Height in Meters", min_value = 0.1)

bmi = weight/(height)**2

st.success(f"Your BMI is {bmi}")

